### ISSUE TITLE
conditional rendering with (&&)

### ISSUE THREAD

**Issue by japiirainen** [raimohanska/harmaja#164]
## description
Conditional rendering using (&&) operator not working as expected.

### current behaviour
crashes with error "*false is not a valid element*".
codesandbox: https://codesandbox.io/s/stupefied-pine-wg8b0u?file=/src/index.tsx

### expected behaviour
I would expect this to work the same way as in React. Eg.
codesandbox: https://codesandbox.io/s/busy-leaf-bg7k0c?file=/src/index.tsx

If this is something *harmaja* want's to support, I would be happy to take a shot at fixing this.

**Comment by raimohanska** [comment]
Ah, yeah. I guess false could be rendered similarly to null. Please do take a shot! There should be a good setup of unit tests to prove it works.

**Comment by raimohanska** [comment]
Here be the test case that you'll likely be changing: https://github.com/raimohanska/harmaja/blob/master/src/harmaja.test.tsx#L183

**Comment by japiirainen** [comment]
looked into this and realised that this feature is already implemented [here](https://github.com/raimohanska/harmaja/commit/189e3fe0a540afdefdb8396cfdb54c19b11e9bfe). So this works after version *0.13.3*. 

I stumbled on this while experimenting with this [codesandbox](https://codesandbox.io/s/todoapp-harmaja-lonna-9xqw5?file=/package.json), which uses harmaja version *0.11.1*.

So if anything, the dependencies of that could be updated. Otherwise this can be closed!☺️

**Comment by raimohanska** [comment]
Haha! I had no recollection whether or not false was supported :) Let’s fix them sandboxes then.
